name: Daily Hot Josh Feed Update

on:
  schedule:
    - cron: '0 11 * * *' # 6 AM Central
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with token
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest feed from bankofentitlement.com
        run: |
          curl -s https://bankofentitlement.com/flashbriefing.json -o flashbriefing.json

      - name: Commit and push updated flashbriefing.json
        run: |
          git config user.name "Hot Josh Bot"
          git config user.email "noreply@bankofentitlement.com"

          if git diff --quiet flashbriefing.json; then
            echo "No changes to commit."
          else
            git add flashbriefing.json
            git commit -m "Daily update from hotjosh_feed.php"
            git push
          fi
