name: Daily Hot Josh Feed Update

on:
  schedule:
    - cron: '0 11 * * *'  # 6:00 AM Central
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest feed from bankofentitlement.com
        run: |
          curl -s https://bankofentitlement.com/hotjosh_feed.php > /dev/null
          curl -s https://bankofentitlement.com/flashbriefing.json -o flashbriefing.json

      - name: Commit and push updated flashbriefing.json
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e

          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git fetch origin
          git checkout -B main origin/main

          git add flashbriefing.json

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automated update: $(date)"
            git push origin main || echo "Push failed but ignored to prevent failure flag."
          fi

          exit 0
