name: Daily Hot Josh Feed Update

on:
  schedule:
    - cron: '0 11 * * *' # 6:00 AM Central Time
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest feed from bankofentitlement.com
        run: |
          curl -s https://bankofentitlement.com/hotjosh_feed.php > /dev/null
          curl -s https://bankofentitlement.com/flashbriefing.json -o flashbriefing.json

      - name: Commit and push updated flashbriefing.json
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git checkout -b update-branch origin/main

          if git diff --quiet flashbriefing.json; then
            echo "No changes to commit."
          else
            git add flashbriefing.json
            git commit -m "Automated update: $(date)"
            git push --force-with-lease origin update-branch:main
          fi
